### PR TITLE
Issue with installing

### PR DESCRIPTION
**Pull request by Nv7-GitHub**
This isn't a PR but an issue, however the Issues tab isn't enabled in the repository settings, so I am making this Issue as a PR.

When I try to install, I get the error
```
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 386, in enable
    mod.register()
  File "/Users/<user>/Library/Application Support/Blender/2.93/scripts/addons/molecular/__init__.py", line 42, in register
    from . import properties, ui, operators
  File "/Users/<user>/Library/Application Support/Blender/2.93/scripts/addons/molecular/operators.py", line 7, in <module>
    from . import simulate, core
ImportError: cannot import name 'core' from 'molecular' (/Users/<user>/Library/Application Support/Blender/2.93/scripts/addons/molecular/__init__.py)
```
I downloaded the Blender 2.9x compatible one, for Mac, and I am using Blender 2.93.

### CODE REVIEW

**Comment by oengelha** [comment]
I have the same issue, but on Windows multiple machines Blender v2.93.1

**Comment by clsack** [comment]
Same issue here. Using Blender 2.93.0 on Linux. Tried with 1.1.2 1.1.2a and 1.1.2b

**Comment by jcnwholland** [comment]
Same here.. tried fixing permissions in windows 10 -- blender 2.93 with no result.
2.92 does work

**Comment by RafaArnalte** [comment]
Same issue here. Using Blender 2.93.1 on Windows 10.

**Comment by MonliH** [comment]
Yes it's broken. However, the [3D-World-UK/Blender-Molecular-Script](https://github.com/3D-World-UK/Blender-Molecular-Script/tree/v2.93) branch worked for me.

`3D-World-UK` actually submitted a PR here already (#7), but for some reason, they closed it.

**Comment by RafaArnalte** [comment]
Please can somebody share the link where to download the zip fixed?

**Comment by scorpion81** [comment]
Ok, I didnt know you have to enable the issues tab manually, but now it is enabled.
Release has been updated by compiling against Python 3.9.x
Closing this issue / PR.

**Pull request closed without merging**
